IPHONEOS_VERSION = '10.3'

inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, IPHONEOS_VERSION
use_frameworks!

# Target Dependencies
target "F.I.T." do    
    pod 'MagicalRecord/Shorthand', '2.2'
	pod 'MZAppearance', '1.1.6'
    pod 'Charts', '3.0.3'
    pod 'ObjectMapper', '2.2.9'
end

# Post-Install Hooks
post_install do |installer|
  set_iphoneos_deployment_target installer
end

def set_iphoneos_deployment_target(installer)
	installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = IPHONEOS_VERSION
    end
  end
end